### ISSUE TITLE
Make a buy order on the gts, so as soon as someone put the pokemon you want you buy it

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#333]
Make a buy order site so you can put in buy orders so you dont need to be looking on gts every 2 seconds to see what people have posted. It would make selling and buying more efficient

**Comment by Rasgnarok** [comment]
Orders would be a complicated concept, and definitely are too variable to properly address them. GTS itself is not moddable easily, and might as well be rewritten. Closing this one simply due to feasibility vs end result. There should be a better GTS interaction for 'wanted' pokemon, but an automatic buy order isn't it.
