### ISSUE TITLE
Warzone additional rules (that are currently enforced)

### ISSUE THREAD

**Issue by SolaceKairos** [SmashMC-Development/Suggestions#450]
**Describe the suggestion**
In warzone, add the rules of
"no potion enhancements" like invisibility, speed, jump boost, ect.
and "glow must be enabled" (/glows)
or have a statement in the rules stating these are not rules

**Which servers does this apply to?**
At least Charizard

**Additional context**
There are some "rules" I see enforced that aren't mentioned in the rules in-game.
The rules I mentioned are ones I've seen enforced by multiple helpers during different times, but are not mentioned in the rules anywhere.

**Comment by Rasgnarok** [comment]
Glows is usually automatically applied on the user, by Warzone itself. Staff should not be enforcing it because it's not a rule, it's a feature. If there was someone that did it, please make a ticket so we can address it. Same thing for potion enhancements - Warzone should be automatically removing enhancements. It is a rule, however.
![image](https://user-images.githubusercontent.com/18584380/118706515-6ed95f80-b7e7-11eb-983c-c5190c836e52.png)
