### ISSUE TITLE
Market Problems

### ISSUE THREAD

**Issue by gabe4552** [SmashMC-Development/Suggestions#457]
The markets in the servers (especially Charizard) are really bad at the moment, things like BP and HA are really becoming worthless as people are massively underselling, for example, a HA mareanie used to be worth about 300k are now worth less than 30k as everyone with a decent amount of money has them. I think that there should be a new rank called like marketing manager or something and they would be able to take things off of the gts and also monitor chat selling under the min price on the gts

**Comment by Rasgnarok** [comment]
It's not simply a matter of enforcing GTS pricing, it's the fact that price is dictated by decay - and there is none in Minecraft.

**Comment by SolaceKairos** [comment]
I've seen staff enforcing anti-underselling but I've noticed that "underselling" is entirely subjective (even between different staff members) due to people valuing things differently. The only consistent pricy thing are legendary papers, high IVs, and a few HA's. (I don't know what BP is but I hear about that too).

**Comment by gabe4552** [comment]
That's the thing I'm saying. BP are maxed ivs but even HA's aren't stable prices a few weeks ago mareanie HA was 200-300k but now they're not even selling for 30k

**Comment by Rasgnarok** [comment]
Forwarded to the main ticket so the discussion can continue!
