### ISSUE TITLE
WZ/ Gigantmax boss idea

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#513]
**Describe the suggestion**
In the new wz update, add a boss that spawns that Gigantamx and up to 4 people can fight together to beat it, If you beat it you get Dynamax candies and other loot and a 30-second cooldown and full heal.

**Which servers does this apply to?**
All.

**Additional context**
You can Dynamax against the boss but only one of u can in the battle and it switches every turn. The Boss When if uses a Gmax move it damages all the pokemon and if 3 pokemon get KOd your team of people lose. And you can heal those who are battling 2. And the Gmax boss can reset the stats off all pokemon ever 3 turns

**Comment by Rasgnarok** [comment]
Doubles, Triples or Quadruples are currently not supported properly within Pixelmon, they are prone to a large number of glitches or don't exist (only Doubles do).

I am still going to be adding this suggestion to our master Warzone ticket, because it would be really fun to have a team inclusion to Warzone's challenges. For example, we could have several bosses spawn in succession, and players have to team up and challenge one of them each, and in beating all 4, rewards are greater than single boss defeats. What do you think?
