### ISSUE TITLE
Changes for WZ

### ISSUE THREAD

**Issue by Joshu-Alzamora** [SmashMC-Development/Suggestions#532]
My suggestion, for the health of the game, and to stay true to other pokemon games, would be to take away the loss of 
a pokemon in WZ. I've given my arguments a lot of thought, and would appreciate your time and feedback wherever possible to better my idea, or to discover why it's a bad idea. My argument ranges from the mechanic being bad for new players, to it gimps team building and discourages creativity, and ultimately can kill a server. 

-It's bad for new players because pokemon being taken can hurt a players chances of being competitive on the server, or worse diminish a players want to continue. Ultimately, new players give health to the game, and new players losing mons is counter productive to them being new and working hard to catch up. 

-Perfect legendary pokemon are rare, breeding isn't easy, and some items are very rare. This all leads to gimp team building when entering warzone because you could easily lose something of extreme value. Unless you're in a dominant clan, pokemon and items of high value become miserable to lose, and can affect someone's team building choices.

-The worst case scenario, obviously, is the death of a server or worse, the entire game. I come from a low pop server, one clan runs the WZ and I've caught several high value almost perfect legendary pokemon. Because it's a low pop server, and their clan is established, it's not fun going into WZ. If I bring my best mons, I risk  losing them, then no longer have access to them and if I don't bring the legendary, I lose to their all legendary team and get kicked from WZ before catching anything. People who always take people pokemon are also suffering, because with each pokemon they take, they discourage a player from trying to catch another good mon just to lose it. I was called out and applauded by the clan running my server for going into WZ 3 or 4 times because it "kept things interesting for them." Meanwhile I'm using a less than optimal team, and not having fun keeping things interesting losing mons I spent days and weeks breeding. This mechanism can kill a game. 

My final thoughts and solution: In no pokemon game does losing a battle result in the loss of a pokemon, but should result in the loss money instead. An argument can be made for it to be an amount of money that would matter, and I would agree. This would make the game healthy again, giving money a reason to be made and could even prevent entry into warzone if funds aren't sufficient. It would feel better to see warzone clans hoarding pokedollars over pokemon. 

All Servers this should apply to. 

N/A

**Comment by DragonBallBreakersRandomizer** [comment]
The first thing is a thing but wz is high risk high reward.

Breeding is meant to be challenging and legends are too common tbh and bp ones are already rare its just people use Iv boosters on it.

The stealing pokemon thing is fun but maybe there could be a way to request stealing money instead. And people sometimes want to take bp legends over money

**Comment by HackuJacku** [comment]
I'm sorry but we won't be adding these suggestions:
- Warzone is intended to be high risk, high reward. The reason behind this is balancing. It has a significantly higher Legendary, Ultra Beast and Shiny rates compared to the rest of the server. Sadly though, Warzone has been losing this due to the players teaming with each other, being "friendly" in Warzone just to AFK for legendaries, buying Warzone protection, ETC. We're currently working on overhauling Warzone from the ground up and the next versions include changes to help mitigate against these issues. 

- Warzone is unique and exclusive to SmashMC. No other servers have anything like this. Multiple servers want it badly and players from other servers constantly suggest it. A large percentage of our player base have joined SmashMC for a range of reasons but one of them being Warzone. 

- Although I haven't been with SmashMC since day 1, Warzone has been part of SmashMC since the early days. We've always had hundreds of players on and we're growing again. If anything, Warzone has been a great addition to help players stay and add enjoyment. Our next version adds some new content to the Warzone which we're exciting for. Therefore, the server is doing the opposite of dying due to Warzone.

- By going to the Warzone, you are at risk of being stolen from. That is your choice if you're going. Warzone has helped to make the server competitive, we are a very competitive based server. 

I believe I have covered your other points and explained why we won't be adding this suggestion.
