### ISSUE TITLE
Safari, an alternative to WZ

### ISSUE THREAD

**Issue by whitesaber31** [SmashMC-Development/Suggestions#542]
**Describe the suggestion**
Many people complained that safari is useless and also some dislike WZ. So, I propose to make safari as the "non pvp legend hunting place". But how do we balance it so legends price doesn't plummet and be as challenging as WZ? I suggest only allow players that go to the safari to only catch pokemons with pokeballs that doesn't have any catch rate boost. For example normal Pokeball, cherish ball, premier ball, heal ball, safari ball, etc. With this, the player will be challenged by PvE instead of PvP and make these balls got some values. I hope you can consider my suggestion.

**Which servers does this apply to?**
Pixelmon servers

**Additional context**
'N/A'.

**Comment by Mikirae** [comment]
Personally, I don’t see a reason to make safari a legend hunting place. The reason Warzone has the high rewards is due to the high risk; safari doesn’t have that.

**Comment by Rasgnarok** [comment]
I agree, Safari just sounds extremely grindy with no real interaction aside from using low-end pokeballs by the hundreds. Declining simply because it doesn't offer a challenge in exchange for rewards, and therefore wouldn't be much more than an easy way to obtain legends without any risk or meaning.
