### ISSUE TITLE
Warzone Timer and Fee

### ISSUE THREAD

**Issue by fellafine** [SmashMC-Development/Suggestions#672]
**Describe the suggestion**
i want to see a the warzone fee and timer gone soon otherwise im quiting.

**Which servers does this apply to?**
All basically but mainly zekrom.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
My In game is RealSaad i think warzone as a place where i feel joy over battling when im in risk of losing pokemon but its all about the competition i was very excited for the new reset but over the last day ive realised theres too many noticeable cons and not many noticeable pros but they one con is the new warzone features. ill start with the fee i dont see this as being that bad but especially when were at the start of our journey and we need money for other stuff then we have the warzone fee we were wanna just pursuit our passion.

Now the worst one, the timer i feel the timer is bad because we cant maintain to keep in warzone we thought we would get alot of time when killing pokemon but all we get is 5 seconds comon something needs to change alot of people are gonna quit if this dosent change.

**Comment by HackuJacku** [comment]
I'm sorry but the Warzone timer and fee will remain. It's intended to be an 'end game' feature and how it was prior to the reset was a way of making large quantities of money for ZERO cost - making money does not and should not occur like this.

Instead of making comments such as "otherwise im quiting", perhaps make constructive suggestions to help us improve the gameplay. This suggestion does not.
