### ISSUE TITLE
Bring back the suggestion channel on discord

### ISSUE THREAD

**Issue by Ipeterson17** [SmashMC-Development/Suggestions#690]
**Describe the suggestion**
In the few months span that I was absent from this server, the suggestion tab was removed and replaced with this GitHub alternative. While I understand the utility of Github, I feel that its suggestions do not reach a majority of the player base, and likewise, does not allow for agreeing/disagreeing with suggestions. I imagine this makes it hard to gauge the popularity of a suggestion, and adding back a suggestions tab to discord would resolve this issue.
 
**Which servers does this apply to?**
Discord 
**Additional context**
N/A

-Shadowslayer685

**Comment by Ipeterson17** [comment]
Additionally, the economy master ticket for the previous reset was very convenient.

**Comment by HackuJacku** [comment]
This is something we will not be doing because it's not feasible. It was EXTREMELY difficult to implement suggestions or resolve bugs via Discord so we switched to GitHub, it has made it far easier to work. 

One thing we could look at for the future is a way to create a GitHub issue via Discord, this is something we've wanted to do for a while now.
