### ISSUE TITLE
Add /unbreed

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Suggestions#697]
**Describe the suggestion**
/unbreed has been removed after the reset. Having the option to unbreed a pokemon would really help the economy on the server.

**Which servers does this apply to?**
All.

**Comment by Restlezzz** [comment]
The warzone will be filled with people with legendaries, and people won't bring their battle perfect mon into warzone because people can just steal your work. Please implement /sts too, it is really harsh for breeders right now unless if the breeders decide to sell bp breedables into gts, which will destroy the economy 1 week into reset.

**Comment by HackuJacku** [comment]
#741
