### ISSUE TITLE
Warzone Spawns and Second to Enter Warzone

### ISSUE THREAD

**Issue by NATEARAY** [SmashMC-Development/Suggestions#738]
**Describe the suggestion**
Warzone is not fun anymore because of the paying to enter, The Legendaries Spawn in the Side of the Warzone and not in the area where players walk through and the Payment to enter warzone is not very good for the economy. I want you to fix Warzone and return it to its old self where players can catch Legendaries with warning in the main chat and no money to enter warzone.

**Which servers does this apply to?**
All the server in PokeSmash 

**Additional context**
P.S: As of now, TheSirud do not like that warzone because of the Money to Enter and without warning in the Main Chat of Legendaries, He did not like the things you guys did in warzone.

**Comment by HackuJacku** [comment]
The Warzone entry fee will remain. It's actually better for the economy because free entry is the part of the reason why the old Warzone reined the previous server's economies.

It's intended that Legendaries spawn all around the map, not near the player. This system will remain. However, we've changed how normal Pokémon spawn though which has significantly improved the spawn rates. I hope these changes improve the situation.
