### ISSUE TITLE
Improvements for warzone that would make it as fun as it used to be.

### ISSUE THREAD

**Issue by SasukeMK2** [SmashMC-Development/Suggestions#771]
okay so ive been in warzone for 10 minute rounds around 8 times and have had 26 spawns and have only ever seen a single legendary. either the spawn proximity is too far away, the legs are glitched or both. either way, it makes the biggest part of the server and the funnest part of the server mundane and boring. fix the proximity of spawns. please. 

Then we also have the ability or move bans in wz. The best part of warzone was to build a competitive team to combat other competitive teams in a way where theres actual risk and reward. now thats basically out of the window.

lastly, add gowstone or something to the floors because at night, it gets way too dark to see anything and i have my brightness on max in a dark room. 

I love smash mc and have put in countless hours to the servers. Please just make the biggest attraction of the server somewhat good.

**Comment by HackuJacku** [comment]
The issue is neither however, we've made a change from the next restart which makes it so the number of spawns around the player is tenfold. 

Based on created suggestions, we decided to ban moves/abilities based on player feedback. You can still build a competitive team as the rules used follow what most of Showdown uses.
