### ISSUE TITLE
Warzone does not spawn every legend!

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Suggestions#803]
**Describe the Issue**
After one and a half month of playing this wipe and a rather shameful ingame time of 26,5 days i have witnessed a very large portion of the warzone spawns and i came to the same conclusion as other people did when i exchanged intel about it.  
_Something seems to be off._ 

**1)** Not every Legendary is able to spawn in the Warzone. Here is the full list of the legends that did not spawn in the span of one month in wz. These statistics are gathered from 75 - mostly consecutive - logfiles from November 1st till November 30th. 
I double checked the legendaries on this specific list by searching for both the legendary name (Only took random samples every 3-5 days) and the wz log code "§8§l>§7 §d§lA §b§l" as well as "§8§l>§7 §4" for the global despawn messages. This list matches with the statements and experience of other players.

- Galarian Articuno
- Ho-Oh (Its spawnset currently has issues)
- Deoxys
- Registeel
- Regice
- Latias
- Rayquaza (Not entirely confirmed)
- Azelf
- Mesprit
- Manaphy
- Phione (Which is good)
- Regigigas
- Shaymin
- Cobalion
- Thundurus
- Diancie
- Magearna
- Type:Null
- Silvally
- Solgaleo
- Tapu Bulu
- Tapu Koko
- Tapu Lele
- Tapu Fini
- Calyrex
- Naganadel (The only UB that does not spawn, poipole spawns frequently tho)

**2)** The Legendaries that spawn the most are mostly those that do not have an original spawn rarity. 
These are: 

- Articuno
- Moltres
- Zapdos
- Mewtwo
- Celebi
- Arceus
- Dialga
- Giratina
- Palkia
- Cosmoem
- Lunala
- Melmetal
- Urshifu
- Galarian Moltres
- Galarian Zapdos

**Are these spawn discrepancies and missing legendary spawns intended?**

**Which servers does this apply to?**
At least Groudon, Reshiram and Kyogre. Possibly other Servers as well. 

**This list will be Updated if anything changes**
_Feel free to add your experience on this topic :)_

**Comment by ghost** [comment]
I play on Groudon and I have noticed the same. Also add Rayquaza to the not spawning list. Haven't seen a single one.

**Comment by Sensouu** [comment]
Other server's opinion: Reshiram player here, I've seen an influx of Victini lately, but other than that your list seems good. Maybe add Kubfu to the "doesn't spawn" list? I haven't seen one of those(I'm chronically online but maybe not online enough to see one, haha)

**Comment by DinglePringleUwU** [comment]
Arjungangwar0
Possible. Data on the spawnrate of Rayquaza is a bit hazy as i have seen him a long time ago in wz as a spawn. 
There is no empirical evidence tho. He does not appear in the logs. I'll be adding him onto the list. Thank you for your input! :)
Sensouu 
I can confirm that an Average of 2,20 Kubfus spawn per day :D! Thank you for your input! :)

**Comment by Sensouu** [comment]
Huh,,, neat.. could you post all the numbers of your findings in a document or In the comments (if you happen to have all the numbers and what not), I’m pretty interested in seeing all the stats of these legendaries (well, at least kyogres but it’s better than nothing). If not, not a big deal, I just would like to see :)

**Comment by DinglePringleUwU** [comment]
> Huh,,, neat.. could you post all the numbers of your findings in a document or In the comments (if you happen to have all the numbers and what not), I’m pretty interested in seeing all the stats of these legendaries (well, at least kyogres but it’s better than nothing). If not, not a big deal, I just would like to see :)

I would rather not provide these informations because actual spawn numbers could alter the worth of some legends. I Only care to see if this is an issue or intended.

**Comment by HackuJacku** [comment]
Love the dedication that you've spent 26.5 days on the server, @DinglePringleUwU! 

In regards to your suggestion though, happy to share exactly how Warzone is configured without disclosing exact values: 897 different Pokémon out of 899, in Pixelmon, can spawn in the Warzone - this does not include regional (Galarian and Alolan) forms but all of them spawn in the Warzone. The only Pokémon which are unable to spawn in the Warzone are Dittos and Ho-Oh with Ho-Oh currently having a bugged spawnset (file used to define the properties of a specific Pokémon's spawning), I keep meaning to fix this.

Therefore, every Legendary in Pixelmon is able to spawn in the Warzone - they all have spawnsets. Like with the whole topic of Pokémon spawning outside of Warzone (again, this is categorically impossible due to how Warzone is both developed and configured), there are no issues with the files as server startup logs would state there's an issue (this is how I know that Ho-Oh's spawnset has issues). 

Therefore, specific Pokémon not spawning comes down to the roll of the dice. All Legendaries have the same rarity (a value used within the spawning system) which means they all have an equal chance of spawning. However, I know what I am saying is occurring because I designed this version of Warzone alongside the developer then proposed it to the rest of the management, throughout development it was vigorously tested and I saw the Legendaries you mention spawn.

Will happily leave this open for you to discuss but to conclude: it's just luck and there are no issues because Warzone has a very indepth error handler which would state if there's an issue with the spawnset.

**Comment by mDerinho** [comment]
Hey all, I agree with this github, I belive the following legendaries should not spawn in WZ 
Articuno/Galar Articuno - Can be obtained from Shrine/ Galar from quest
Moltres - Can be obtained from Shrine
Zapdos - Can be obtained from Shrine
Mewtwo - Can be cloned from mew
Dialga - Can be obtained from red chain/Altar
Palkia - Can be obtained from red chain/Altar
Giratina - Can be obtained from red chain/Altar
Arceus - Can be obtained from plates/chalice
Phione - Can be breed from Manaphy with ditto
Meltan - Can obtain from smelting iron
"Potentially Ho-oh and lugia" - because you can get them via the respective Bells

Because that these legendaries spawning very frequently in WZ apart from phione it highly reduces the value of these pokemon, and their respective items, Before the WIPE as the red chain trio has not spawned that much the red chain was worth around 200K, now i can not imagine anyone paying anything similar to that for a very rare and hard item to get

The bird trio cost 50K at the shrines + time filling up an orb, and they are currently getting sold for around 15-20K , making the shrines useless as these spawn frequently also

Arceus plates are now harder to get than before the wipe but arceus seems to spawn quite alot too,  his price should be higher for the effort that it takes to get him

Mewtwo in my personal opinion shoudlnt spawn in WZ because he reduces the value of Mew that does not spawn all that frequent, As we know you can clone mewtwo and have 3 attempts from every Mew, which makes it hard to get a Mewtwo, and because of the high spawn rates in WZ alongside mewtwo spawning i've already seen a couple of very high IV mewtwos

Meltan has a chance to spawn beside you if you smelt iron, and this is a fun mechanic, although i dont think players will try to go for this challange as meltan has probably some of the highest spawn rates in WZ


Some legendaries that i personally have never saw spawned or saw once and  I have quite a extensive playtime myself are for example
Rayquaza
Calyrex
The lake trio - Azelf , Mespirit and Uxie
Tapu koko, tapu bulu, tapu fini , tapu lele
Diance
Cobalion
Shaymin

**Comment by WalkAway7** [comment]
I disagree with this.
Yes it defaces the value of these legends, but only by a small amount. If we take away enough from the warzone, there will be no incentive to go into warzone at all, I for one and I'm sure others will agree with me, but one of the only reasons people go into warzone is to capture nice legends.

**Comment by mDerinho** [comment]
I mean i agree with you walkaway but if dialga's , palkia's, zapdoses etc spawn so frequently it totally ruins their value, why would someone try get a red chain and go through all that hassle, And i meant it halfs the values if not more for some legends 50k to 15k for the trio birds, 80k-20/40k for the creation trio for example

**Comment by WalkAway7** [comment]
Well, the legends don't spawn as frequently, and there are tons of legends, it will still be a grind to get legends, whatever way you see it from.

**Comment by HobnobberJunior** [comment]
> Therefore, specific Pokémon not spawning comes down to the roll of the dice. All Legendaries have the same rarity (a value used within the spawning system) which means they all have an equal chance of spawning. However, I know what I am saying is occurring because I designed this version of Warzone alongside the developer then proposed it to the rest of the management, throughout development it was vigorously tested and I saw the Legendaries you mention spawn.

I do not exactly get what you mean by this Hacko. So you are saying that there is an equal chance of all legends spawning right? So if we had a thousand spawns we should in theory have the same amount of all legendaries right? If this is the case then I do not understand the frequencies of the legend spawns, which we currently have. We have a large majority of some spawns and next to none of other if not 0. Do u mind explaining this for me?

**Comment by mDerinho** [comment]
> Well, the legends don't spawn as frequently, and there are tons of legends, it will still be a grind to get legends, whatever way you see it from.

They do tho thats the reason im posting this, im active and i see how many legs spawn, prices of legendaries are low as of right now , especially the Altar ones comparing to the asking price of 50k to get it

**Comment by mDerinho** [comment]
> > Therefore, specific Pokémon not spawning comes down to the roll of the dice. All Legendaries have the same rarity (a value used within the spawning system) which means they all have an equal chance of spawning. However, I know what I am saying is occurring because I designed this version of Warzone alongside the developer then proposed it to the rest of the management, throughout development it was vigorously tested and I saw the Legendaries you mention spawn.
> 
> I do not exactly get what you mean by this Hacko. So you are saying that there is an equal chance of all legends spawning right? So if we had a thousand spawns we should in theory have the same amount of all legendaries right? If this is the case then I do not understand the frequencies of the legend spawns, which we currently have. We have a large majority of some spawns and next to none of other if not 0. Do u mind explaining this for me?

I agree, what you kind of said is unclear hacko, as it doesnt add up with the actual rates of legendaries spawning (apart from ho-oh)

**Comment by HobnobberJunior** [comment]
> > Therefore, specific Pokémon not spawning comes down to the roll of the dice. All Legendaries have the same rarity (a value used within the spawning system) which means they all have an equal chance of spawning. However, I know what I am saying is occurring because I designed this version of Warzone alongside the developer then proposed it to the rest of the management, throughout development it was vigorously tested and I saw the Legendaries you mention spawn.
> 
> I do not exactly get what you mean by this Hacko. So you are saying that there is an equal chance of all legends spawning right? So if we had a thousand spawns we should in theory have the same amount of all legendaries right? If this is the case then I do not understand the frequencies of the legend spawns, which we currently have. We have a large majority of some spawns and next to none of other if not 0. Do u mind explaining this for me?

Just adding to this. I am willing and im sure DinglePringleUwU is aswell, to count exactly how many legends thats spawn in wz and exactly which spawn (and ofc documenting it), to prove that not all legends spawn at the same rate. We could make a statistic over the frequencies, because what we are seeing now do match with that u are saying.

**Comment by ghost** [comment]
@HackuJacku I understand that you don't see any problems on the backend. But, statistically speaking all 6 servers can't have such bad luck. Most regular players on the servers say that they have not seen some of the legends in warzone. You should not chalk this to bad luck. I think it needs further investigation. Thank You.

**Comment by DinglePringleUwU** [comment]
> In regards to your suggestion though, happy to share exactly how Warzone is configured without disclosing exact values

**Thank you** very much for explaining it in detail! Not adding Ditto shows - yet again - that you guys knew beforehand what you were doing, because you can get it fairly easy from the raids. Neatly balanced. Wz in general is an amazing feature that brings me back to this server everytime i think of pokemon. It is so much fun and the current wz is the best wz i have ever witnessed.

And well, yes. Maybe it just comes down to RNG or maybe my statistics are incorrect/faulty.
However the pattern that i see seems to disagree with that thesis as the odds of +100 Urshifus build a strong contrast to 0 of any of those legs i mentioned. Maybe the legendaries have a succesful spawn attempt without an actual spawn (This happened frequently before wipe with larger legends like Reshiram in Ultraspace. The spawn attempt was still shown as succesful with /ll). It would also explain why the error handler is not giving out any signs. I will try to double check this with /poketracker as it also currently shows the spawns inside wz.

**I would highly suggest** to keep an eye on this topic.


_Also... Has anyone ever seen a Scorbunny in wz? A Venusaur maybe? No?
But surely a very, very high amount of Blastoise. Odd, right?_

**Comment by HackuJacku** [comment]
Hopefully this explanation is clearer: each Pokémon has a 'weight' to spawn, weights aren't percentages (for example: from Arceus has a weight of 0.75, the percentage of Arceus spawning is 0.75 divided by the sum of all weights loaded (we'll call this 899 as that's the number of Pokémon in Pixelmon), * 100 - this would mean Arceus has a 0.083% chance of spawning when a spawning cycle occurs AND the Pokémon is not on a cooldown.

The values I've used aren't what are used, they're examples. However, the weight of each Legendary is the same so they have an equal chance of spawning. 

Each Legendary also has a specific time of day associated to it which means they can't always spawn (e.g: Darkrai can only spawn at night or Cresselia might only spawn at dawn), these conditions decrease how common the Pokémon is. Some Legendaries have a bigger time window than others to spawn (e.g: during the day) whereas others might be shorted (e.g: dusk). 

If you're struggling to understand that, please let me know. It's important to understand the whole system because statistically, you can't calculate it without this knowledge and the values used for the spawner. 

I was asked last week if Landorus, Thundurus and Tornadus spawned in the Warzone, which I responded to yes. Yes because i) they're configured to be and ii) I've seen them spawn multiple times throughout makes changes or working on other stuff. 

Over my lunch, I had a quick look incase I was wrong and here are the outcomes (these are taken from Rayquaza as that's the server I had open but everything is the same):
[ERROR] 26/11/2021 05:24:17 SpawnSet has null species! Filename: Ho-Oh - (shows that Ho-Oh doesn't spawn due to the issue I mentioned).

These are just some of the Pokémon which spawned in the Warzone over a 2 day period:
[INFO] 26/11/2021 06:15:55 Legendary spawned: Pokemon{Landorus} BlockPos{x=29, y=67, z=25}
[INFO] 26/11/2021 06:16:02 Legendary spawned: Pokemon{Zygarde} BlockPos{x=-214, y=86, z=-16}
[INFO] 26/11/2021 06:18:37 Ultra Beast spawned: Pokemon{Kartana} BlockPos{x=88, y=71, z=29}
[INFO] 26/11/2021 06:30:38 Legendary spawned: Pokemon{Tornadus} BlockPos{x=-173, y=87, z=83}

[INFO] 26/11/2021 07:12:50 Legendary spawned: Pokemon{Heatran} BlockPos{x=-46, y=67, z=-49}
[INFO] 26/11/2021 07:37:51 Legendary spawned: Pokemon{Zamazenta} BlockPos{x=31, y=84, z=-52}
[INFO] 26/11/2021 07:45:05 Ultra Beast spawned: Pokemon{Celesteela} BlockPos{x=70, y=69, z=-70}
[INFO] 26/11/2021 07:55:55 Legendary spawned: Pokemon{Kyurem} BlockPos{x=-208, y=104, z=-122}
[INFO] 26/11/2021 07:59:40 Legendary spawned: Pokemon{Palkia} BlockPos{x=-33, y=67, z=-65}
[INFO] 26/11/2021 08:02:06 Ultra Beast spawned: Pokemon{Guzzlord} BlockPos{x=76, y=99, z=-125}
[INFO] 26/11/2021 08:02:27 Legendary spawned: Pokemon{Yveltal} BlockPos{x=-22, y=67, z=-38}
[INFO] 26/11/2021 08:16:47 Legendary spawned: Pokemon{Genesect} BlockPos{x=27, y=67, z=35}
[INFO] 26/11/2021 08:30:12 Ultra Beast spawned: Pokemon{Stakataka} BlockPos{x=116, y=154, z=143}
[INFO] 26/11/2021 08:39:46 Ultra Beast spawned: Pokemon{Blacephalon} BlockPos{x=-42, y=87, z=-11}
[INFO] 26/11/2021 08:49:16 Legendary spawned: Pokemon{Cosmoem} BlockPos{x=-220, y=93, z=77}
[INFO] 26/11/2021 09:07:13 Ultra Beast spawned: Pokemon{Nihilego} BlockPos{x=-170, y=90, z=97}
[INFO] 26/11/2021 09:10:12 Ultra Beast spawned: Pokemon{Buzzwole} BlockPos{x=-76, y=86, z=-8}
[INFO] 26/11/2021 09:11:39 Legendary spawned: Pokemon{Regirock} BlockPos{x=141, y=116, z=-89}
[INFO] 26/11/2021 09:14:05 Legendary spawned: Pokemon{Uxie} BlockPos{x=110, y=70, z=66}
[INFO] 26/11/2021 09:49:12 Legendary despawned: Pokemon{Xerneas} BlockPos{x=-109, y=107, z=127}
[INFO] 26/11/2021 09:58:32 Legendary spawned: Pokemon{Moltres} BlockPos{x=-37, y=76, z=35}
[INFO] 26/11/2021 10:23:03 Legendary spawned: Pokemon{Kyogre} BlockPos{x=-21, y=156, z=156}
[INFO] 26/11/2021 10:23:15 Legendary spawned: Pokemon{Suicune} BlockPos{x=-53, y=84, z=104}
[INFO] 26/11/2021 10:44:49 Legendary spawned: Pokemon{Groudon} BlockPos{x=-101, y=92, z=-100}
[INFO] 26/11/2021 10:56:13 Legendary spawned: Pokemon{Marshadow} BlockPos{x=103, y=69, z=-60}
[INFO] 26/11/2021 10:56:26 Legendary spawned: Pokemon{Darkrai} BlockPos{x=112, y=81, z=-24}
[INFO] 26/11/2021 11:14:17 Legendary spawned: Pokemon{Reshiram} BlockPos{x=-100, y=88, z=77}
[INFO] 26/11/2021 11:19:32 Ultra Beast spawned: Pokemon{Poipole} BlockPos{x=-267, y=155, z=-60}
[INFO] 26/11/2021 11:48:01 Legendary spawned: Pokemon{Mew} BlockPos{x=-88, y=81, z=-89}
[INFO] 26/11/2021 11:50:32 Legendary spawned: Pokemon{Kubfu} BlockPos{x=-166, y=105, z=108}
[INFO] 26/11/2021 12:34:33 Legendary spawned: Pokemon{Articuno} BlockPos{x=-86, y=99, z=-121}
[INFO] 26/11/2021 12:48:33 Legendary spawned: Pokemon{Regidrago} BlockPos{x=118, y=73, z=34}
[INFO] 26/11/2021 12:56:52 Legendary spawned: Pokemon{Necrozma} BlockPos{x=6, y=92, z=-107}
[INFO] 26/11/2021 12:57:21 Legendary spawned: Pokemon{Zamazenta} BlockPos{x=101, y=69, z=-44}
[INFO] 26/11/2021 13:44:23 Legendary spawned: Pokemon{Dialga} BlockPos{x=-175, y=87, z=-65}
[INFO] 26/11/2021 13:45:27 Legendary spawned: Pokemon{Meltan} BlockPos{x=-212, y=92, z=-77}
[INFO] 26/11/2021 14:43:08 Legendary spawned: Pokemon{Entei} BlockPos{x=-148, y=89, z=39}
[INFO] 26/11/2021 14:56:04 Legendary spawned: Pokemon{Genesect} BlockPos{x=94, y=71, z=16}
[INFO] 26/11/2021 15:04:55 Legendary spawned: Pokemon{Virizion} BlockPos{x=-244, y=109, z=-63}
[INFO] 26/11/2021 15:05:05 Legendary spawned: Pokemon{Keldeo} BlockPos{x=-154, y=87, z=-73}
[INFO] 26/11/2021 15:35:09 Legendary spawned: Pokemon{Zarude} BlockPos{x=52, y=88, z=127}
[INFO] 26/11/2021 15:54:44 Legendary spawned: Pokemon{Terrakion} BlockPos{x=-100, y=69, z=-25}
[INFO] 26/11/2021 16:46:32 Legendary despawned: Pokemon{Zacian} BlockPos{x=-98, y=91, z=-106}
[INFO] 26/11/2021 16:51:48 Legendary spawned: Pokemon{Eternatus} BlockPos{x=-256, y=166, z=-149}
[INFO] 26/11/2021 18:29:58 Legendary spawned: Pokemon{Raikou} BlockPos{x=117, y=72, z=56}
[INFO] 26/11/2021 19:00:44 Legendary spawned: Pokemon{Victini} BlockPos{x=-90, y=95, z=122}
[INFO] 26/11/2021 20:37:54 Ultra Beast spawned: Pokemon{Xurkitree} BlockPos{x=-190, y=87, z=24}
[INFO] 26/11/2021 21:45:23 Legendary spawned: Pokemon{Glastrier} BlockPos{x=68, y=84, z=104}
[INFO] 27/11/2021 01:45:41 Legendary spawned: Pokemon{Zekrom} BlockPos{x=-225, y=88, z=19}

I'll keep looking but you can see a lot of Legendaries do spawn. Please note that some are more common than others.

**Comment by HackuJacku** [comment]
Forgot to add, these logs don't show the Regional form name (e.g: Galarian or Alolan) but I'm seeing a lot of Articuno spawns. I can't tell you if these are Galarian or not sadly :/

**Comment by HobnobberJunior** [comment]
Hi Hacko. I get what you mean now, however I still have a difficulty understanding something. I do not understand how we can one type of legendary spawn SO many times  and some where we have not seen once. I would think that with this many hours/days of playing time, we would have gotten at least one of the Tapus. I simply cannot see in what circumstance we wouldn't get one of them. I get that they have different conditions which they need to spawn and weight, I just do not see that it is this unlikely that they will spawn.

**Comment by DinglePringleUwU** [comment]
> If you're struggling to understand that, please let me know. It's important to understand the whole system because statistically, you can't calculate it without this knowledge and the values used for the spawner.

I do understand that now and honestly it makes much more sense now. My statistics would not matter, as the rarity of all legendary/UB wz-spawns are predetermined due to their spawn time and weight value. 
Is there maybe any pattern in those seemingly missing legendaries that i listed? Like their spawn time or their respective Weight value? 

Edit: Ofc not asking for their exact values. Keep those to yourself. :)

**Comment by HackuJacku** [comment]
> Hi Hacko. I get what you mean now, however I still have a difficulty understanding something. I do not understand how we can one type of legendary spawn SO many times and some where we have not seen once. I would think that with this many hours/days of playing time, we would have gotten at least one of the Tapus. I simply cannot see in what circumstance we wouldn't get one of them. I get that they have different conditions which they need to spawn and weight, I just do not see that it is this unlikely that they will spawn.

It would be due to the time they spawn at. The legendaries which spawn the most have the longest spawn times (day, night, etc) whereas the ones which are rarer have times which are sorted (dawn, dusk, etc). I tested it on my mirror server when I removed the other legendaries, they spawned

**Comment by HobnobberJunior** [comment]
How long do we in principle have to wait for the "rare" legendaries to spawn to actually confirm, that we actually have a chance to get them in wz?

**Comment by HobnobberJunior** [comment]
> How long do we in principle have to wait for the "rare" legendaries to spawn to actually confirm, that we actually have a chance to get them in wz?

I know you said it works Hacko, it does just seem like a very long time that we have to wait tho.

**Comment by HackuJacku** [comment]
> How long do we in principle have to wait for the "rare" legendaries to spawn to actually confirm, that we actually have a chance to get them in wz?

There's no waiting time, it doesn't work like that as I've explained above.

Looked through 3 log files so far, bunch more unique spawns (again, more Legendaries spawned than this)
[INFO] 27/11/2021 08:41:58 Legendary spawned: Pokemon{Spectrier} BlockPos{x=-194, y=87, z=-75}
[INFO] 27/11/2021 11:10:08 Legendary spawned: Pokemon{Regieleki} BlockPos{x=-115, y=87, z=70}
[INFO] 27/11/2021 11:29:30 Legendary spawned: Pokemon{Glastrier} BlockPos{x=-179, y=88, z=-16}
[INFO] 27/11/2021 13:48:00 Legendary spawned: Pokemon{Latios} BlockPos{x=-144, y=96, z=-123}
[INFO] 27/11/2021 15:46:28 Legendary spawned: Pokemon{Hoopa} BlockPos{x=-178, y=87, z=47}
[INFO] 27/11/2021 19:14:02 Legendary spawned: Pokemon{Meloetta} BlockPos{x=-133, y=95, z=-116}

[INFO] 28/11/2021 00:10:29 Legendary spawned: Pokemon{Cresselia} BlockPos{x=-176, y=87, z=49}
[INFO] 28/11/2021 02:08:05 Legendary spawned: Pokemon{Lugia} BlockPos{x=-16, y=72, z=39}
[INFO] 28/11/2021 06:24:43 Legendary spawned: Pokemon{Zeraora} BlockPos{x=25, y=76, z=64}

**Comment by arjungangwar0** [comment]
Okay...maybe I get you point that Rayquaza spawns times are dusk/dawn, lowering it's chance of spawning. But, I have been playing since the beginning of the reset and I have not seen any of the Tapus spawn. The thing is Rayquazas are actually spawning in wild, several have. But, I have to seen a single tapu spawn in wild or in wz. Moreover, these legends should have better chances of spawning in wz compared to wild because of sheer amount of spawns in wz. But, legends like Rayquaza have spawned more times in overworld than in wz.  Maybe something to investigate or think about.

**Comment by ghost** [comment]
@HackuJacku Ok so if the chance of legs like Tapu is decreased due to their spawn timings maybe you need to increase it's weight slightly to increase the spawn?

PS: I deleted the last comment because I missed couple of comments above which basically answered what I was saying.

**Comment by DinglePringleUwU** [comment]
> I have to seen a single tapu spawn in wild or in wz

Every legendary can spawn in the wild @arjungangwar0 

![2021-11-29_12 05 08](https://user-images.githubusercontent.com/94211853/144269377-64886010-6003-4a0a-a6a4-2fe3fff1e731.png)
The lack of tapu spawns comes because tapus only spawn in a normal Jungle and most people prefer Jungle M due to Mew spawns. And leg spawns are only visible if you are in the same dimension. If you really want a tapu, than you can get a tapu. (Even tho the leg spawnrate will make this quite a challenge so combine it with ha hunting)

However, never have seen any tapu in wz. Or heard of them spawning in wz.

**Comment by ghost** [comment]
You are missing the point I am trying to make. The issue is with them not spawning in wz.

**Comment by DinglePringleUwU** [comment]
True that.

**Comment by ghost** [comment]
@HackuJacku so where do we stand on this suggestion?

> @HackuJacku Ok so if the chance of legs like Tapu is decreased due to their spawn timings maybe you need to increase it's weight slightly to increase the spawn?
> 
> PS: I deleted the last comment because I missed couple of comments above which basically answered what I was saying.

**Comment by Mikirae** [comment]
This suggestion is something that is being looked in to and worked on :)

**Comment by ghost** [comment]
ok thanks for the update :)

**Comment by DinglePringleUwU** [comment]
**Update: Nothing changed.**

The legendaries i listed still have not spawned in wz even once in this month as well. 
The legendaries that are not on the list i posted originally however, all spawned without any problems.
Again: **This is not just my impression**, but the impression of everyone that goes to the warzone.

Were the players this month just unlucky again?

**Comment by Mikirae** [comment]
> **Update: Nothing changed.**
> 
> The legendaries i listed still have not spawned in wz even once in this month as well. The legendaries that are not on the list i posted originally however, all spawned without any problems. Again: **This is not just my impression**, but the impression of everyone that goes to the warzone.
> 
> Were the players this month just unlucky again?

Already said that it's something we're looking into. We know there's a problem, but it's not as simple as "Just fix it lol"

**Comment by HobnobberJunior** [comment]
However an update or anything would be nice. Since we get no information it feels kinda pointless to wait.

Oh and just as a little sidenote, we got told that there wasn't even an issue.

**Comment by Mikirae** [comment]
The update is that it's not fixed but still being looked into. Regardless
if it's not done at all or right about to be done, these legends would not
spawn. If you don't want to go into Warzone because these legends don't
spawn, that's perfectly fine and you're free to wait until we're done :)
Sorry that I don't have better news, but unfortunately things on the
backend aren't always simple.

**Comment by HobnobberJunior** [comment]
I made another post today on increasing the legend spawns out of wz. Is this a thing that could be done relatively easy so we can atleast hunt legends outside of wz? Bc as of right now next to no legends spawn outside of the wz.

**Comment by Mikirae** [comment]
This is something that I plan on doing in the coming days here :)

**Comment by HobnobberJunior** [comment]
Alright, sounds good. Please keep us updated :)

**Comment by DinglePringleUwU** [comment]
The last thing we heard was that "it's just luck and there are no issues because Warzone has a very indepth error handler which would state if there's an issue with the spawnset.".
There was no update on wether or not this was an actual issue/problem until now. That is why i wanted to wait and collect some more intel on that so i could ask again with more certainty. 

Good luck with fixing it.

**Comment by ghost** [comment]
mhm let me be honest here....ppl are losing interest because a lot of things of server are not functioning properly and people have start feeling the previous iteration of the server was better. Plus, some of the ppl are just annoyed and leaving server because of waiting and improper/inadequate communication. I, myself, am visiting like twice a week and playing less in general because I feel like this was a major issue and you guys were not even acknowledging it....which felt bad because most of the active players on each server were complaining about this issue.

**Comment by Mikirae** [comment]
I put in the thread that it was something we were actively looking into. I
can't update you guys every step of the way while we're doing things, as
that's just not how it works.
We are doing our literal best. We are working hours on end every single day
and are met with nothing but people telling us that we are terrible at our
jobs and everything is breaking. We fix bug reports as fast as we can and
have people turn around to us and tell us "Everything is broken" and not
specify anything beyond that.
You're entitled to be frustrated, that's perfectly fine, but we're
frustrated as well.

**Comment by ghost** [comment]
The only time you updated us in this thread was when I pinged Hacko which was to be exact 27 days ago. Don't you think it is a long time to go without any update on such a major issue when you are playing regularly on the server? You guys at least owe explanation to the people here on GitHub who are actively spending so much of their time for improvement of the server. Did you see the detailed explanation and analysis of @DinglePringleUwU...don't you think it took time? All I am saying is there needs to be better communication. We all appreciate the work you guys are putting in...that's why we are here to help you fix things.

**Comment by Mikirae** [comment]
No, I don't. When I played on other servers, I wasn't even told that people
were investigating things. People would report it, and it would eventually
be fixed. We will not be updating you guys every step of the way,
unfortunately, as there is quite literally nothing to say other than it is
being worked on in the development side of things.
I'm sorry if that's not to your liking, but unfortunately that's just how
it is.

**Comment by ghost** [comment]
If you think, the the server don't need to update the people spending their time to help it...that's your discussion. Just would be nice to be updated once in a while.

**Comment by Mikirae** [comment]
I did give an update. I told you that we are working on it. As I've said,
I've never seen another server, or any game company for that matter, tell
people that they are in the process of backend development of things
multiple times during the course of fixing a bug or issue. There's not
really much else to say here, but take care :)
We try to update things that are new when we get a chance, but oftentimes
we're busy.

**Comment by DinglePringleUwU** [comment]
Closed, all legs can spawn.
