### ISSUE TITLE
Respond to the bugs and glitches forum.

### ISSUE THREAD

**Issue by SiennaAffliction** [SmashMC-Development/Suggestions#841]
**Describe the suggestion**
It looks like no one ever even looks at the bugs and glitches page, and if they have, why wouldn't they even respond with a (can't fix it right now but we're working on it). It would make players actually feel like there being listened to and not just a number for the server. people pay actual money for things in this server. 
I don't understand why there is so little interaction between staff and players.

**Which servers does this apply to?**
Probably every server, the interaction between staff/helpers and actual players is next to none. 

**Additional context**
N/A

**Comment by HackuJacku** [comment]
https://discord.com/channels/526879084534562827/831991625873489990/931541754920960041
This is factually untrue and has never been accurate. Yes, there are A LOT of open issues but majority of the time we're waiting on a response from the individual due to a lack of information provided. We're unable to do much or anything based on lack of information.
