### ISSUE TITLE
Legend spawns

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Suggestions#845]
Improve the rates of legend spawns. At this point in time, only having a 5% chance for legend spawn seems to be way too low. The legends hardly ever spawn and it makes it a real pain to ever get close to finishing the dex. Even with hours of afk in a certain biome with multiple possible legend spawnsm will not give a spawn. Even when hardly any people are playing on the server no legends will spawn. This and wz not spawning every legend, takes the fun out of hunting legends and trying to complete the dex. Therefore I think either a higher legend spawnrate out of wz or a larger variety in wz is needed.

**Which servers does this apply to?**
Kyogre or all servers

**Comment by DinglePringleUwU** [comment]
>Even with hours of afk in a certain biome

literally weeks*

It is frustrating and even more so if legendary pokemon just despawn upon spawn.
(No joke, that still happens from time to time even with enough place to spawn)

And when you try to get a rare spawn that only occurs in Dusk/Dawn it will take weeks of 24/7 afking. After fixing the overworld legendary spawn, things became even harder to get because there are more players the spawn could occur onto.
Trying to fill the dex is not enjoyable by any means. Just look at this picture!

![2021-12-27_19 22 32](https://user-images.githubusercontent.com/94211853/147499431-405a502b-35cf-473e-9361-f6b325740aec.png)

**Comment by Mikirae** [comment]
Natural legend spawns are being adjusted heavily here in the next couple of days :)

**Comment by Mikirae** [comment]
This has been done :)
