### ISSUE TITLE
Move Relearner in warp mart or pokecenter

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Suggestions#877]
I wanna suggest about if the Staff should make a new Move Relearner like on the old Servers were we had 1 in the /warp mart i think it would be really useful and take out the annoying afking for it

**Comment by IAmF3rdie** [comment]
I agree with this. It would be a great addition to the server, with all the legends we catch from WZ it would be great to relearn the moves we otherwise couldn't get from the specific legend because its way passed the level. an example would be Urshifu's "main" move which is learned level 10 and below (i think)

**Comment by Mikirae** [comment]
This has been done :)

**Comment by Firemelon66** [comment]
Lil question what u mean with this has been done?

**Comment by Firemelon66** [comment]
Like u guys added 1 now? And if yes where?

**Comment by Mikirae** [comment]
[image: image.png]
/warp moves
