### ISSUE TITLE
Please change HA Limitations.

### ISSUE THREAD

**Issue by ChiraqAlerts** [SmashMC-Development/Suggestions#882]
I really want the HA Limitations to change, The current limitations being that you cannot breed for the continued lineage of Hidden Ability on Pokemon unless you are the original trainer. I suggest that we are instead allowed to sell off hidden ability Pokemon but via a special system that forces you to pay atleast a minimum price of whatever seems fair. This system only being for Hidden Abiltiy Pokemon.
I feel like it's been ruining alot of the fun of making friends on here, you can't really make deals involving HA's with your friends, you can't sell it off for help with breeding if you dont know how, It really limits the social interaction on the server and makes it feel way more dry in my opinion.

Any Pixelmon Server on the SmashMC Network that has this limitation.

N/A
![unknown](https://user-images.githubusercontent.com/97918939/149839119-36c9ba35-7cf9-4dda-8a22-1565bd893279.png)

**Comment by HobnobberJunior** [comment]
Not being able to breed other players HAs is one of the best changes that has been made since last reset. It makes it worth actually hunting HAs that people want. I strongly disagree with this. There is still ways to trade/deal with HA's, you just ask for money instead. I do not see why it is necessary for you to also be able to breed the HA to be able to make a deal. 
Besides that, eco is different for each server, making a general minimum price pointless.

**Comment by Mikirae** [comment]
HAs were done this way to improve the economy, and so far it has had the effect that we've wanted. While we appreciate your suggestion, we don't have any plans of changing the way that Hidden Abilities work.
