### ISSUE TITLE
Wz megas

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Suggestions#936]
**Describe the suggestion**
I wish for warzone to only have megas, understand if this don't get added but its worth a try, the reason I think its should be mega only is how op dynamax is, its just really unfun to have to play it and use it, it completely make megas useless since they get way outclassed by dynamax. It would be more fun and competitive if it were to be only megas (also would make more people buy mega stone keys)

**Which servers does this apply to?**
all servers

**Additional context**
N/A

**Comment by SlotMach1n3** [comment]
I agree to this

**Comment by ThePapaChunks** [comment]
Megas would make the wz alot more competitve its always easy to bring a broken mon throw it in the back and wait for the end of a battle and easily sweep with max moves and it also completely makes megas unviable as there not very powerful compared to dmax. also I believe alot more people would like mega over dmax because of just how outright broken dmax is and megas will make the wz more competitve in the end. So I agree with Dwag0n in the situation and I think banning dmax should def be looked into.

**Comment by DinglePringleUwU** [comment]
That is a bad idea.
It would make any gigantamax form irrelevant and would ultimately reduce the activity in wz - given that not everybody has spare megastones to bring into wz. Dynamax candy, max soup and Z-Crystals would also become unwanted items.
While the intention of making Mega-pokemons more interesting is a good thing, it would ultimately only limit the options a player has in wz.

**Comment by FadeFire** [comment]
Personally i think the thought isnt wrong, but dynamax/galgantamax makes the wz a lot more competetive since its easier to get than a megastone and less of a risk, so basically some guy can come in with throws but due to the dmax still be a treath. So when it comes to competitiveness the current wz is better, though i must say i generally agree that dmax might be OP sometimes but it definetely can be countered and needs to be used wisely in order to win a fight. Megas are still a very viable option as people on my server have shown me before, i dont think they are even, but i dont think mega is useless against dmax.  So overall i think that even if dmax might be a bit OP i think it is still fairly balanced and would make the game more dry and boring if removed, it just adds an extra joker that can still be countered completly.

**Comment by ThePapaChunks** [comment]
> Personally i think the thought isnt wrong, but dynamax/galgantamax makes the wz a lot more competetive since its easier to get than a megastone and less of a risk, so basically some guy can come in with throws but due to the dmax still be a treath. So when it comes to competitiveness the current wz is better, though i must say i generally agree that dmax might be OP sometimes but it definetely can be countered and needs to be used wisely in order to win a fight. Megas are still a very viable option as people on my server have shown me before, i dont think they are even, but i dont think mega is useless against dmax. So overall i think that even if dmax might be a bit OP i think it is still fairly balanced and would make the game more dry and boring if removed, it just adds an extra joker that can still be countered completly.

Smogon banned dmax because of it being op but have never banned the mega feature as they have banned certain mega's in the past. And dmax doesnt make anything more competitve, it was banned due to being op and proceeded to stay banned and never tested by Smogon so many mons can easily abuse dmax like Kartana.

**Comment by DinglePringleUwU** [comment]
>Smogon banned dmax because of it being op 

That is kinda framed as it is lacking of important details. 
Smogon banned it for OU and then for UBER format. It is however allowed in AG - and warzone is AG. Zacian is also AG. Everyone is using it. 
Banning dynamax in wz would essentially mean limiting the WZ to the Uber format that gets toppled over by Zacian. Thus banning dmax in wz would only make sense - if we talk about the smogon format - if a ban of AG would come with it.

**Comment by morrow12** [comment]
d max is just no skill mega is way more fun and competitive and makes people wanna fight in wz

**Comment by ajdawg48** [comment]
Dmax is just no fun playing against at all really. I think taking it out of warzone would be a good way to make it more competitive. Also to the person saying how zacian would be too good without it you are just wrong tbh there are many ways to counter zacian without dmax. So this would not be making it unfair in any way just more competitive.

**Comment by morrow12** [comment]
For example Zacians counter is ha quagsire there we go counters without  d max at all, Make it like mega cancels dmax like last reset.

**Comment by Sadkeemstar112** [comment]
Agreed dynamax ruins the game

**Comment by Firemelon66** [comment]
In my oppinion Mega would be way better in wz since it makes it more competitive and dynamax is on certain mons bugged and way to op like on charizard and it takes no skill to sweep with it

**Comment by Rasgnarok** [comment]
Accepted, has now been added to the network.
