### ISSUE TITLE
Having access to all kits prior to current rank

### ISSUE THREAD

**Issue by Happi1223** [SmashMC-Development/Suggestions#951]
**Describe the suggestion**

Pretty clear idea, if you have a rank above elite at the moment you can not use kits below the current rank besides ace because of an apparent bug issue. So what I am saying is that if you have a rank you should be able to access all kits for ranks below your current rank so for example if you are legend, you have access to kit mythic, elite and ace and so on for smash. When you pay for the rank you are paying for better perks, and the kit regardless how many people use it. But for the current idea the server has in place you dont have access to those kits and essentially when you pay 25USD to go from elite to mythic you are only buying the perks for 25$ and that ranks kit while currently losing your previous kit. Any server Ive played whether it was pixelmon, factions, prisons Ive had ranks on majority of those servers and all of them gave you access to every kit for the ranks below your current rank as well as the kit for your current rank. This would eventually give the kits more meaning to the ranks as you get another kit to use which adds value to that rank/

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
All
**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
Also maybe buffing the kits a little better perhaps make them more used because right now theyre pretty underwhelming now yes I understand you dont wanna make the server p2w with kits etc but even just adding some xp candies in there or something a little more to make them want to be used by the players more and not just as a little bonus to the rank perks

**Comment by Mikirae** [comment]
The reason that we went away from this as it was hard to balance kits that were cumulative. It ended up that, when we were making the kits, even adding just one more thing to each of the kits made it very overpowered; this was because of what we wanted to have in the kits, combined with the fact that they were cumulative.
We had to make the choice to either completely change what we wanted in the crates, or make it so each kit simply _added_ to the previous kit, and then disabled the previous kit with each rank up.
You're not losing anything when you rank up, it's just adding on to the previous kit by a little bit.
