### ISSUE TITLE
Taking held items off after WZ loss

### ISSUE THREAD

**Issue by llnama** [SmashMC-Development/Suggestions#981]
Players take off their held items after a loss in warzone, ahem sanguinolency. Sorry, little cough. There is no repercussions even after they lie to staff and proof is shown. 
I have an idea how this problem could be solved, but may not be the best. Make the player not be able to open their inventory, nor throw a pokemon out (they can switch items that way too) until the opponent has selected a steal. I know the 30 secs of picking a pokemon might be long, so there's that downside, but it's just an initial idea I had.

Applies to All servers.

Thanks!

**Comment by Mikirae** [comment]
I unfortunately don't think this is possible. I know that previously I had wanted held items during Random Tournaments, but I was told there was no event that developers could check in order to prevent an item from being removed.
And I don't think there's any way to prevent an inventory from being opened either, unfortunately :(
